"""empty message

Revision ID: 0a5dd039ddc0
Revises: d2ecf6eba905
Create Date: 2019-01-23 23:42:37.999291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5dd039ddc0'
down_revision = 'd2ecf6eba905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schedule', sa.DateTime(), nullable=False),
    sa.Column('function_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timer')
    # ### end Alembic commands ###
