"""timers: add enabled field

Revision ID: 0fbb63d18415
Revises: 816b477c7611
Create Date: 2025-02-03 11:56:29.585016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.mutable import MutableDict

# revision identifiers, used by Alembic.
revision = '0fbb63d18415'
down_revision = '816b477c7611'
branch_labels = None
depends_on = None
Session = sessionmaker()
Base = declarative_base()

class Timer(Base):
    __tablename__ = "timer"
    id = sa.Column(sa.String, primary_key=True)
    schedule = sa.Column(sa.DateTime(timezone=True), nullable=False)
    function_id = sa.Column(sa.String, nullable=False)
    enabled = sa.Column(sa.Boolean, default=True, nullable=False)
    data = sa.Column(MutableDict.as_mutable(sa.JSON), nullable=False, default=lambda: {})
    auto_delete = sa.Column(sa.Boolean)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('enabled', sa.Boolean()))
    bind = op.get_bind()
    session = Session(bind=bind)
    for timer in session.query(Timer):
        timer.enabled = True
    session.commit()
    op.alter_column('timer', sa.Column('enabled', sa.Boolean(), nullable=False))


def downgrade():
    op.drop_column('timer', 'enabled')

