"""Track last_seen in DB

Revision ID: 42eae3f77164
Revises: 1b9b2f51e5c8
Create Date: 2017-08-30 22:23:37.677052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42eae3f77164'
down_revision = '1b9b2f51e5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_seen',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_seen')
    # ### end Alembic commands ###
