"""empty message

Revision ID: 6494eb528fb5
Revises: 68740fb25fbd
Create Date: 2021-08-05 23:02:34.923226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6494eb528fb5'
down_revision = '68740fb25fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_state', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_state', 'data')
    # ### end Alembic commands ###
