"""add auto-delete column for timers

Revision ID: 68740fb25fbd
Revises: 9f899f1fe66e
Create Date: 2021-08-04 20:43:16.930755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68740fb25fbd'
down_revision = '9f899f1fe66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('auto_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer', 'auto_delete')
    # ### end Alembic commands ###
