"""Add trends table to reduce number of states

Revision ID: 694dbe6eda54
Revises: 661f15cfb036
Create Date: 2021-03-14 16:13:57.082709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694dbe6eda54'
down_revision = '661f15cfb036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trends',
    sa.Column('thing_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Interval(native=True), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('t_min', sa.Float(), nullable=True),
    sa.Column('t_avg', sa.Float(), nullable=True),
    sa.Column('t_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['thing_id'], ['thing.id'], ),
    sa.PrimaryKeyConstraint('thing_id', 'start')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trends')
    # ### end Alembic commands ###
