"""Move last_seen back into Thing

Revision ID: b61f281339df
Revises: d27acdb53cfa
Create Date: 2020-04-05 19:05:24.897198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b61f281339df'
down_revision = 'd27acdb53cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_seen')
    op.add_column('thing', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thing', 'last_seen')
    op.create_table('last_seen',
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('device_id', name='last_seen_pkey')
    )
    # ### end Alembic commands ###
