"""add a display name field for timer table

Revision ID: baa06bb41a51
Revises: 0fbb63d18415
Create Date: 2026-01-07 16:34:38.764237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa06bb41a51'
down_revision = '0fbb63d18415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('display_name', sa.String(), nullable=True))
    op.execute("update timer set display_name=id;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer', 'display_name')
    # ### end Alembic commands ###
