"""Add monotonic_offset to Thing

Revision ID: c76cb7622612
Revises: 0fbb63d18415
Create Date: 2026-05-31 17:02:03.695397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76cb7622612'
down_revision = '0fbb63d18415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thing', sa.Column('monotonic_offset', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thing', 'monotonic_offset')
    # ### end Alembic commands ###
