"""empty message

Revision ID: d27acdb53cfa
Revises: 09666637ea0f
Create Date: 2020-04-05 18:04:52.454095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27acdb53cfa'
down_revision = '09666637ea0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thing_view',
    sa.Column('thing_id', sa.Integer(), nullable=True),
    sa.Column('view_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(('thing_id', ), ['thing.id'], ),
    sa.ForeignKeyConstraint(('view_id', ), ['view.id'], ),
    sa.PrimaryKeyConstraint('thing_id', 'view_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thing_view')
    op.drop_table('view')
    # ### end Alembic commands ###
