"""empty message

Revision ID: d5604118823b
Revises: 6494eb528fb5
Create Date: 2022-01-06 19:54:47.018281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5604118823b'
down_revision = '6494eb528fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
