"""re-add last_seen

Revision ID: dd00c26615e7
Revises: b61f281339df
Create Date: 2020-04-08 21:25:11.748535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd00c26615e7'
down_revision = 'b61f281339df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_seen',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.drop_column('thing', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thing', sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_table('last_seen')
    # ### end Alembic commands ###
