"""empty message

Revision ID: f913db1fc4d4
Revises: 6494eb528fb5
Create Date: 2023-08-13 11:18:34.146133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f913db1fc4d4'
down_revision = '6494eb528fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thing', sa.Column('ordering', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thing', 'ordering')
    # ### end Alembic commands ###
